[Feature] LoginPage 제작
Team18-The-Julge/main_repo pull request #56
Opened 2024-04-27 05:23 UTC by kong33

## #️⃣연관된 이슈

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
로그인 페이지 제작 
radio 버튼 제작
axios 코드 수정

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> 아직 스타일링 적용이 되지 않았습니다.
> 모달이 열리지 않는데 혹시 봐주실 수 있나요 ? @naeun14 
> 우선 코드를 먼저 올리고 머지 전에 계속 리펙토링 후 푸시하겠습니다.
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-04-27 10:33 UTC, jinhok96 commented on src/components/feature/LoginForm/LoginFom.tsx
> +          </Button>
```tsx
  return (
    ...
    <ModalGroup.Trigger disableToggle>
      {버튼컴포넌트}
    </ModalGroup.Trigger>
    ...
  )
```
이렇게 감싸면 모달 열립니다! 버튼을 클릭하면 자동으로 모달이 열리게 되는데, disableToggle을 넣어주면 이걸 방지합니다. 원할 때 모달을 열고 싶으면 `const { toggle } = useModal();`로 toggle 함수를 가져온 뒤 필요한 곳에서 호출하면 열고 닫을 수 있어요.
```tsx
  ...
  // 기존 코드의 isModalOpen과 동일합니다.
  const [openModal, setOpenModal] = useState<ReactElement | null>(null);
  // 모달을 토글하는 함수입니다.
  const { toggle } = useModal();

  // 모달을 닫을 때 호출할 함수입니다.
  const handleClickCloseModal = {
    onError: () => {},
    onSubmit: () => {
      router.push(pageList.shopDetail(shopId));
    }
  };

  // 모달을 설정합니다.
  const modalList = {
    // eslint-disable-next-line react/no-unstable-nested-components
    onError: (message: string) => <Modal.Error onClick={handleClickCloseModal.onError}>{message}</Modal.Error>,
    onSuccess: <Modal.Check onClick={handleClickCloseModal.onSubmit}>수정이 완료되었습니다.</Modal.Check>
  };

  // 폼 제출 서버 응답 성공 함수입니다.
  const onSuccess = () => {
    setOpenModal(modalList.onSuccess); // 열고싶은 모달을 저장합니다.
    toggle(); // 모달을 토글합니다.
  };

  // 폼 제출 서버 응답 실패 함수입니다.
  const onError = (e: AxiosError) => {
    if (axios.isAxiosError(e) && e.response) {
      const { message } = e.response.data as { message: string };
      console.log('message', message);
      setOpenModal(modalList.onError(message));
      toggle();
    }
  };

  // 폼 제출 함수입니다.
  const onSubmit = () => {
    // 폼 데이터 업로드
    // 서버에 폼을 제출할 때 onSuccess, onError에 따라 모달을 토글합니다.
    putShop(putShopPayload, { onSuccess, onError });
  };

  ...
  
  // JSX
  return (
    ...
    <ModalGroup.Trigger disableToggle>
      <Button size="large" solid submit active>
        {status.login.buttonText}
      </Button>
    </ModalGroup.Trigger>
    ...
    <ModalGroup.Content>{openModal}</ModalGroup.Content>
    ...
  )
```

2024-04-27 10:34 UTC, jinhok96 requested changes
모달 관련 코멘트 남겼습니다!

2024-04-28 13:20 UTC, min3eo approved these changes

2024-04-28 16:18 UTC, naeun14 approved these changes

2024-04-28 16:18 UTC, kong33 commented on src/components/feature/LoginForm/LoginFom.tsx
> +          </Button>
저는 trigger 버튼이 아니라 state 로 관리하기 위해서useModal 훅을 조금 수정해 open 함수를 빼서 사용했습니다! 혹시 변경사항인지하시면 좋을 것 같아 코드 첨부합니다!
```
function ModalProvider({ children }: defaultProps) {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  const close = () => setIsOpen(false);
  const open = () => setIsOpen(true);
  const toggle = () => setIsOpen((prev) => !prev);

  return (
    // eslint-disable-next-line react/jsx-no-constructed-context-values
    <ModalContext.Provider value={{ isOpen, close, open, toggle }}>{children}</ModalContext.Provider>
  );
}
```

2024-04-28 16:59 UTC, merged